### ISSUE TITLE
Segments not working

### ISSUE THREAD

**Issue by DutchWorkX3D** [ProjectsWithRed/nanoleaf#4]
![IMG_7816](https://github.com/ProjectsWithRed/nanoleaf/assets/131209550/48f0a9f7-bf7d-45ba-8ea0-59365c917e63)
I have followed the manual and checked everything, uploaded the code to the esp32 but when turning on it only lights up the first digit fully and the second digit 2 segments.

In series mode the same.

It looks like it only turns on 87 leds instead of segmenting them.

I checked all the wiring and when turning on all leds by setting the amount of leds to 261 the turn on.
also checked the schematics and they are spot on with your manual.

**Comment by ProjectsWithRed** [comment]
What is the exact issue you are facing? It looks like from the picture your LEDs are cut in segments of 1 LED, so you need to update the length accordingly which I think you found out to be 261. This is mentioned in the video at [10:56](https://youtu.be/RalzwaIh_J4?si=Q3jefhQwZ3zCQtOd&t=656).

**Comment by LimeDexx** [comment]
Yes, I have exact the same length of led strips per segment as you have,
every box has one ledstrip with 9 leds and divided into 3 segments

28 x 3 + 3 = 87

28 times 9 leds = 252 + 9 (total individual addressable leds of 28 + the 1 extra strip of 9 as you discribe in your video)

**Comment by LimeDexx** [comment]
Oh and sorry, Limedexx = Dutchworkx

**Comment by LimeDexx** [comment]
Yes, with the setup as I described, how many leds should I fill in because now only 87 leds are on istead of all

**Comment by ProjectsWithRed** [comment]
Your calculation is correct, however, for the extra strip, in your case it will just be 3 rather than 9. You just need 3 addressable leds as extra on the start.

**Comment by LimeDexx** [comment]
Yes but in your video you have a strip of 9 and you set the total leds to 87
![Screenshot 2024-01-21 165254](https://github.com/ProjectsWithRed/nanoleaf/assets/157263583/cf23ab66-61fb-4e39-acf6-34f29efe0fc7)

**Comment by ProjectsWithRed** [comment]
In my case, every 3 LEDs are addressable as seen by the cuts, so 9 LEDs for me is only 3 addressable sections of the strip. I don't know exactly which LED strips you have but from the image you sent, it looks like each LED is separately addressable.

**Comment by LimeDexx** [comment]
ok there we go, so in my case yes every light is addressable, what amount should I use then 9 sections per strip ?

**Comment by ProjectsWithRed** [comment]
As many as you need to fit across the whole segment housing, and just update the variable `ADDR_LEDS_PER_SEG` found here `WLED/usermods/NanoLeaf_Display/usermod_nanoleaf_display.h` to match, more details can be found in the [readme](https://github.com/ProjectsWithRed/nanoleaf) regarding this.

**Comment by LimeDexx** [comment]
Thank you very much for your help, it is working as it should be now :-)

**Comment by LimeDexx** [comment]
by the way, I have remixed the box with printable diffuser so you will not need any other materials anymore.

**Comment by ProjectsWithRed** [comment]
Perfect! Sounds good, if you want, push the 3D model to the repository of the diffuser and we can make it part of the 3D models, so other people may use it.
